//
// Generated file, do not edit! Created by nedtool 5.7 from message/ConfirmationMsg.msg.
//

#ifndef __CONFIRMATIONMSG_M_H
#define __CONFIRMATIONMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>message/ConfirmationMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ConfirmationMsg
 * {
 *     int packetId = 5;
 *     int senderId;
 *     int receiverId;
 * }
 * </pre>
 */
class ConfirmationMsg : public ::omnetpp::cPacket
{
  protected:
    int packetId;
    int senderId;
    int receiverId;

  private:
    void copy(const ConfirmationMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConfirmationMsg&);

  public:
    ConfirmationMsg(const char *name=nullptr, short kind=0);
    ConfirmationMsg(const ConfirmationMsg& other);
    virtual ~ConfirmationMsg();
    ConfirmationMsg& operator=(const ConfirmationMsg& other);
    virtual ConfirmationMsg *dup() const override {return new ConfirmationMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getReceiverId() const;
    virtual void setReceiverId(int receiverId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConfirmationMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConfirmationMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONFIRMATIONMSG_M_H

