//
// Generated file, do not edit! Created by nedtool 5.7 from message/ErrorMessage.msg.
//

#ifndef __STD_ERRORMESSAGE_M_H
#define __STD_ERRORMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include <bits/stdc++.h>
typedef std::vector<int> Route;
// }}


namespace std {

/**
 * Class generated from <tt>message/ErrorMessage.msg:28</tt> by nedtool.
 * <pre>
 * packet ErrorMessage
 * {
 *     int packetId = 6;
 *     int receiverId;
 *     int deadNodeId;
 *     Route route;
 * }
 * </pre>
 */
class ErrorMessage : public ::omnetpp::cPacket
{
  protected:
    int packetId;
    int receiverId;
    int deadNodeId;
    Route route;

  private:
    void copy(const ErrorMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ErrorMessage&);

  public:
    ErrorMessage(const char *name=nullptr, short kind=0);
    ErrorMessage(const ErrorMessage& other);
    virtual ~ErrorMessage();
    ErrorMessage& operator=(const ErrorMessage& other);
    virtual ErrorMessage *dup() const override {return new ErrorMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getReceiverId() const;
    virtual void setReceiverId(int receiverId);
    virtual int getDeadNodeId() const;
    virtual void setDeadNodeId(int deadNodeId);
    virtual Route& getRoute();
    virtual const Route& getRoute() const {return const_cast<ErrorMessage*>(this)->getRoute();}
    virtual void setRoute(const Route& route);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ErrorMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ErrorMessage& obj) {obj.parsimUnpack(b);}

} // namespace std

#endif // ifndef __STD_ERRORMESSAGE_M_H

