//
// Generated file, do not edit! Created by nedtool 5.7 from message/ResponseMessage.msg.
//

#ifndef __STD_RESPONSEMESSAGE_M_H
#define __STD_RESPONSEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include <bits/stdc++.h>
typedef std::vector<int> Route;
// }}


namespace std {

/**
 * Class generated from <tt>message/ResponseMessage.msg:27</tt> by nedtool.
 * <pre>
 * packet ResponseMessage
 * {
 *     int packetId = 4;
 *     int receiverId;
 *     Route route;
 *     int hops;
 * }
 * </pre>
 */
class ResponseMessage : public ::omnetpp::cPacket
{
  protected:
    int packetId;
    int receiverId;
    Route route;
    int hops;

  private:
    void copy(const ResponseMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ResponseMessage&);

  public:
    ResponseMessage(const char *name=nullptr, short kind=0);
    ResponseMessage(const ResponseMessage& other);
    virtual ~ResponseMessage();
    ResponseMessage& operator=(const ResponseMessage& other);
    virtual ResponseMessage *dup() const override {return new ResponseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getReceiverId() const;
    virtual void setReceiverId(int receiverId);
    virtual Route& getRoute();
    virtual const Route& getRoute() const {return const_cast<ResponseMessage*>(this)->getRoute();}
    virtual void setRoute(const Route& route);
    virtual int getHops() const;
    virtual void setHops(int hops);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResponseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResponseMessage& obj) {obj.parsimUnpack(b);}

} // namespace std

#endif // ifndef __STD_RESPONSEMESSAGE_M_H

